function c = cCoefficient(P, beta, Tinit)
    [lambdaS, lambdaG, ~] = geomConstants(P, beta);
    eb = P.cS*(P.Tm - Tinit);
    c = P.rho*P.v*eb ...
        + lambdaS*P.alphaS*(P.T - Tinit) ...
        + lambdaG*P.alphaG*(P.T - P.Ta) ...
        + lambdaG*P.epsilon*P.sigmaSB*(P.T^4 - P.Ta^4);
end